// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsEzASpwkeZeYzJbHWv6QQhfNls70hGLQ',
    appId: '1:467572779341:web:4462ae8e076b8b6341af04',
    messagingSenderId: '467572779341',
    projectId: 'app-shoppinglist-795d6',
    authDomain: 'app-shoppinglist-795d6.firebaseapp.com',
    databaseURL: 'https://app-shoppinglist-795d6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app-shoppinglist-795d6.appspot.com',
    measurementId: 'G-3FE2TVYLEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHR22uXZYEo0sIrOAlJZNQrOzQBIjC_50',
    appId: '1:467572779341:android:42b935e92aa6c1fa41af04',
    messagingSenderId: '467572779341',
    projectId: 'app-shoppinglist-795d6',
    databaseURL: 'https://app-shoppinglist-795d6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app-shoppinglist-795d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEH7e-eN8O1jwuqUnbNZym6x5EwAOvkWM',
    appId: '1:467572779341:ios:bd3aa0565e3a3a8841af04',
    messagingSenderId: '467572779341',
    projectId: 'app-shoppinglist-795d6',
    databaseURL: 'https://app-shoppinglist-795d6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app-shoppinglist-795d6.appspot.com',
    iosBundleId: 'com.example.ff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEH7e-eN8O1jwuqUnbNZym6x5EwAOvkWM',
    appId: '1:467572779341:ios:bd3aa0565e3a3a8841af04',
    messagingSenderId: '467572779341',
    projectId: 'app-shoppinglist-795d6',
    databaseURL: 'https://app-shoppinglist-795d6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app-shoppinglist-795d6.appspot.com',
    iosBundleId: 'com.example.ff',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsEzASpwkeZeYzJbHWv6QQhfNls70hGLQ',
    appId: '1:467572779341:web:2c860ea8dc6053a241af04',
    messagingSenderId: '467572779341',
    projectId: 'app-shoppinglist-795d6',
    authDomain: 'app-shoppinglist-795d6.firebaseapp.com',
    databaseURL: 'https://app-shoppinglist-795d6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app-shoppinglist-795d6.appspot.com',
    measurementId: 'G-Z5RFXP0DWC',
  );
}
